Create pro-audio-setup.md
openSUSE/openSUSE-docs-revamped-temp pull request #11
Opened 2021-07-25 12:28 UTC by LyrixCaz

I plan to contribute documentation on getting setup with pro audio. - 15cents

2021-07-27 17:06 UTC, apinter requested changes
Some minor grammar issues which should be fixed, but TBH I dislike the overall tone of the doc... Feels more like reading a very pushy blog post than the official openSUSE docs. 
It should be a bit more friendly (check the other docs present for reference) and couldn't really figure what is the "pro audio" bit coming from the doc. Frankly I thought it is a package ^_^
Anyhow, please review it again, fix the grammar and the tone.

2021-07-27 17:06 UTC, apinter commented on project/docs/pro-audio-setup.md
> +- First and foremost if you are planning to do low latency audio/voice recording, it is **imperative** that you get a sound interface be it an USB, Firewire, or PCI card; your performance will be mil
Why this tone? Would be a lot more polite if you would recommend the use of xyz hardware not **ordering** the reader to get out of their way and get one...

2021-07-27 17:06 UTC, apinter commented on project/docs/pro-audio-setup.md
> +**[To be continued..]**
Is this a WIP?

2021-07-27 18:33 UTC, LyrixCaz commented on project/docs/pro-audio-setup.md
> +- First and foremost if you are planning to do low latency audio/voice recording, it is **imperative** that you get a sound interface be it an USB, Firewire, or PCI card; your performance will be mil
I understand

2021-07-27 18:34 UTC, LyrixCaz commented on project/docs/pro-audio-setup.md
> +**[To be continued..]**
Yes

2021-07-27 18:37 UTC, LyrixCaz commented on project/docs/pro-audio-setup.md
> +- First and foremost if you are planning to do low latency audio/voice recording, it is **imperative** that you get a sound interface be it an USB, Firewire, or PCI card; your performance will be mil
Ill see what the overall tone is.

2021-07-27 21:32 UTC, why-not-try-calmer commented on project/docs/pro-audio-setup.md
> +- First and foremost if you are planning to do low latency audio/voice recording, it is **imperative** that you get a sound interface be it an USB, Firewire, or PCI card; your performance will be mil
It's you first PR so that's understable @LyrixCaz! I agree with @apinter and I am sure he too believes that this can become a great first PR!

My suggestions, in decreasing order of importance:
1. imagine you're explaining everything to a 13 year old who knows nothing but is smart (I don't even know what "Pro Audio" means or refers to).
2. explain exactly where you want to move the reader (goal), why this goal is important (the "problem" it solves), and all the assumptions you make
3. try to be a bit more specific where you think this document should go in the overall documentation (that will be easier after you've described the "problem" it solves).

2021-07-27 21:54 UTC, LyrixCaz commented on project/docs/pro-audio-setup.md
> +- First and foremost if you are planning to do low latency audio/voice recording, it is **imperative** that you get a sound interface be it an USB, Firewire, or PCI card; your performance will be mil
Thank you! I'll review accordingly

2021-08-03 19:46 UTC, Ethanol6 commented on project/docs/pro-audio-setup.md
> +- First and foremost if you are planning to do low latency audio/voice recording, it is **imperative** that you get a sound interface be it an USB, Firewire, or PCI card; your performance will be mil
At the moment there isn't much in the docs between "just listening to sound" and "pro studio setup". It would be beneficial to start this doc very simple for those who just want to edit some audio on occasion. Such a use case would not require much in terms of computer hardware. (Personally I still use a dual core laptop with 4GB of RAM and Generic kernel to record with and latency is fine). Then get more complicated. Hardware recommendations are not so easy to make since you cannot guess what software someone is going to use. Instead try to explain the relationship between software and hardware and under what conditions someone should consider upgrading their hardware.

2021-08-04 21:41 UTC, LyrixCaz commented on project/docs/pro-audio-setup.md
> +- First and foremost if you are planning to do low latency audio/voice recording, it is **imperative** that you get a sound interface be it an USB, Firewire, or PCI card; your performance will be mil
I see, that does make alot of sense. I was thinking sort of a 'balls to the wall' audio production machine.

2021-08-17 10:57 UTC, apinter requested changes

2021-08-17 10:57 UTC, apinter commented on project/docs/pro-audio-setup.md
> + `# zypper ar -fp90 https://download.opensuse.org/repositories/home:/geekositalia:/daw/openSUSE_Tumbleweed/ Geekosdaw`
IIRC I pointed this out on Telegram as well, but `home` repos should really not be recommended to any users. Was there any effort made to get the team to submit it to Factory? If no I honestly don't want this to be merged here.

2021-08-17 13:13 UTC, why-not-try-calmer commented on project/docs/pro-audio-setup.md
> + `# zypper ar -fp90 https://download.opensuse.org/repositories/home:/geekositalia:/daw/openSUSE_Tumbleweed/ Geekosdaw`
Yeah it's already difficult to get Factory things to get covered in these docs so I have to agree.

2021-08-17 13:24 UTC, why-not-try-calmer commented on project/docs/pro-audio-setup.md
> + `# zypper ar -fp90 https://download.opensuse.org/repositories/home:/geekositalia:/daw/openSUSE_Tumbleweed/ Geekosdaw`
Sorry @lyrixcaz we have been under scrutiny recently for including too many things and the very criterion for inclusion I have put forward is quite clearly incompatible with home repos. However in view of the effort and the improved quality of this PR I'd like to suggest you to host these contents on an openSUSE wiki. When the recipe is free of home repos, it will become easier for us to host it according to our criterion.

Again, I hope this is not a disappointment for you, and I apologize for the inconvenience. The situation around these docs is evolving quickly and we need to react to various sorts of influence.

2021-08-17 19:43 UTC, Ethanol6 commented on project/docs/pro-audio-setup.md
> + `# zypper ar -fp90 https://download.opensuse.org/repositories/home:/geekositalia:/daw/openSUSE_Tumbleweed/ Geekosdaw`
Most of what this doc sets out to do can be done without the home repo. To say it is a "crucial" step is an opinion based on someones personal workflow. This is OK, why we like `git` is to have the ability to peer review content before it lands and have sensible discussion about it. Also the recent events demonstrate that we need to tighten up a bit. 

@LyrixCaz This PR is a bit premature and there doesn't seem to be much work going into it right now. Remember, merging a PR into this repository makes it immediately available to users at the (temporary) hosting site.

I'm closing this PR until the document has had some work to bring it in line with the recommendations.

2021-08-17 19:43 UTC, closed without merging