Simple method for clinging on to outdated kernels for the sake of survival
openSUSE/openSUSE-docs-revamped-temp pull request #53
Opened 2021-09-20 23:36 UTC by why-not-try-calmer

2021-09-21 21:17 UTC, Idesmi approved these changes
Looks alright to me.

2021-09-22 09:30 UTC, why-not-try-calmer commented
Ok for you too @apinter ?

2021-09-24 12:43 UTC, apinter commented
Yea, it is alright, however I would include the option to keep different versions of the kernel by deafult as it is described here: https://en.opensuse.org/SDB:Keep_multiple_kernel_versions

2021-09-28 15:22 UTC, apinter requested changes

2021-09-28 15:22 UTC, apinter commented on project/docs/updating_upgrading_reverting.md
> +As it happens, the Linux kernel sometimes undergoes regressions. For the end user this often translates into issues where the system has trouble communicating with the hardware. The user could rollba
IMO this should include that this config file should be configured right after a fresh installation otherwise it if fairly pointless if the problem is already present.

2021-09-28 15:22 UTC, apinter commented on project/docs/updating_upgrading_reverting.md
> +## tumbleweed-cli
As I pointed it out [here](https://t.me/opensuse_docs/5458) I strongly believe that we should offer solution and not potentially introduce more problems. We could replace `tw-cli` with locking the kernel with `zypper` as it is equally a bad idea. Remove it please.

2021-09-28 15:31 UTC, why-not-try-calmer commented on project/docs/updating_upgrading_reverting.md
> +As it happens, the Linux kernel sometimes undergoes regressions. For the end user this often translates into issues where the system has trouble communicating with the hardware. The user could rollba
By the way the new contents means that it's now safe to remove all the instructions about locking. Multiversion makes locking superfluous.

2021-09-28 15:36 UTC, why-not-try-calmer commented on project/docs/updating_upgrading_reverting.md
> +## tumbleweed-cli
I suggest I remove everything about locking since it has no purpose anymore with multiversion. tw-cli is presented below for the "preventive mode", which none of the dev/maintainer I've heard about this criticizes for (see https://www.reddit.com/r/openSUSE/comments/ptqo2u/comment/hdxzeq1/?utm_source=share&utm_medium=web2x&context=3 and below). The criticism I've heard so far targets only:
- rolling back (if I need to change this, fine, but let's talk about this in a different PR)
- the health evaluation algorithm (already warned and disclaimed against).

2021-09-28 15:44 UTC, apinter commented on project/docs/updating_upgrading_reverting.md
> +## tumbleweed-cli
`tw-cli` is promoting falls use of snapshots and it is an incredibly poor choice of tool for reverting changes. `snapper` and the default subvolume configuration of `btrfs` is there for a reason. I will be painfully honest here and further cut any unnecessary debate on this: I will not let this land in this doc.

2021-09-28 19:11 UTC, why-not-try-calmer commented on project/docs/updating_upgrading_reverting.md
> +## tumbleweed-cli
I am a bit confused. You would not have approved the approved PR at https://github.com/openSUSE/openSUSE-docs-revamped-temp/pull/24? That one is the PR that introduced tw-cli into this document. 

Now the current PR has nothing to do with that; it barely changed a few words pertaining to tw-cli. So are you suggesting a revert? 

More generally, where in these docs do you suggest tw-cli go, in view of the fact that __the preventive use__ (i.e. moving from the current snapshot to snapshot `hello, I am not the latest snapshot but I am fairly recent and the user have evidence that I'll be kind to him` has many users (from Dario Faggioli to Fabian Vogt going through the comments from the reddit post linked above)? (As for the __rollback__ use, there is a consensus that it is unsafe and I am glad to remove or recommend against it.

2021-09-28 19:44 UTC, apinter commented on project/docs/updating_upgrading_reverting.md
> +## tumbleweed-cli
> I am a bit confused. You would not have approved the approved PR at #24? Or have you changed your mind? Because that one is the PR that introduced tw-cli into this document.

Would've not and did not

> Now the current PR has nothing to do with that; it barely changed a few words pertaining to tw-cli. So are you suggesting a revert?

Remove it entirely. Why would we recommend essentially an experimental tool as a safety net to anybody? :thinking: 

> More generally, where in these docs do you suggest tw-cli go, in view of the fact that **the preventive use** (i.e. moving from the current snapshot to snapshot `hello, I am not the latest snapshot but I am fairly recent and the user has evidence that I'll be kind to him` has many users (from Dario Faggioli to Fabian Vogt going through the comments from the Reddit post linked above)? (As for the **rollback** use, there is a consensus that it is unsafe and I am glad to remove or recommend against it.

I believe that I made my stand on this matter really clear in the past and also on Telegram fairly recently therefore I fail to understand the confusion. I would suggest an entirely different section for experimental and controversial tools such as this, maybe under _Completing and fine-tuning your setup_. It has absolutely no place to mix with out-of-the-box tools that provide a proper safety net for the users. I'm not saying don't document it, but be responsible about it.

2021-09-28 20:42 UTC, why-not-try-calmer commented on project/docs/updating_upgrading_reverting.md
> +## tumbleweed-cli
Oh I probably read too much into your comments. If it just a matter of copy-pasting elsewhere that's not a problem.

2021-09-29 07:52 UTC, why-not-try-calmer commented on project/docs/updating_upgrading_reverting.md
> +## tumbleweed-cli
Okay done @apinter.

2021-09-29 16:54 UTC, apinter requested changes

2021-09-29 16:54 UTC, apinter commented on project/docs/updating_upgrading_reverting.md
> +## More community resources relevant to updating
Remove this please.

2021-09-29 17:06 UTC, why-not-try-calmer commented on project/docs/updating_upgrading_reverting.md
> +## More community resources relevant to updating
yup

2021-09-30 05:01 UTC, apinter approved these changes

2021-09-30 07:59 UTC, merged