Adrien/safety usability on tw
openSUSE/openSUSE-docs-revamped-temp pull request #55
Opened 2021-09-28 14:02 UTC by why-not-try-calmer

Please don't merge before #53 as it builds on it.

2021-10-02 09:18 UTC, why-not-try-calmer commented
@apinter any comments?

2021-10-04 05:03 UTC, apinter requested changes

2021-10-04 05:03 UTC, apinter commented on project/docs/safety_usability.md
> +This might appeal to advanced users who agree to spend more time configuring their system in exchange for a system that will require little to no maintenance (especially suited for friends and relati
I think the whole point of MicroOS is to not configure as much as one would on a regular desktop like TW. The whole idea of MicroOS is to set it up once and forget about it while using it for one thing only - in this case as a Desktop -. I think this sentence's second half is contradicting the first and overall contradicting the sentence at line 46. 
If it's not recommended for new user why recommend it to "friends and relatives" ^_^ 
Probably need to word it a bit better.

2021-10-04 05:04 UTC, apinter commented on project/docs/safety_usability.md
> +3. Update every other week or twice a month, not more often. Use `sudo zypper dup`, plus if that applies to you, `flatpak update`.
FTR the flatpak units are just a suggestion, do ignore if not needed.

2021-10-04 07:59 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +- don't use the "1-click installers" available from https://software.opensuse.org
Okay, but let's not take risks, how long will this linger around, I don't know. I don't want to take bets. Every soul we can save from these traps should be saved.

2021-10-04 08:01 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +2. Do not manually install important system libraries or codecs directly from _zypper_ or _Yast2_. Use [opi](/best-of-post#codecs) if you must, but prefer software that ship with their own static lib
I 100% agree. Currently the wording of this point implies: flatpaks > self-contained static libs > opi. My reasoning is that someone cannot find or use an application within the first two groups, it's ok for them to use opi.

2021-10-04 08:13 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +3. Update every other week or twice a month, not more often. Use `sudo zypper dup`, plus if that applies to you, `flatpak update`.
> "not more often" - that doesn't seem right. This bit seem to encourage a use of TW that will get the user stuck on old snapshots and I would recommend removing this. Maybe reword it as: "3. Update at least every other week or twice a month. Use `sudo zypper dup`, plus if that applies to you, `flatpak update`." Flatpaks can be automatically updated with `Gnome-software` or `Discover`. If, however we recommend against using those tools here's a short systemd unit to take care of the updates automatically:
> 
> ```
> # vim /etc/systemd/system/update-flatpaks.timer
> [Unit]
> Description=Update user Flatpaks daily
> 
> [Timer]
> OnCalendar=daily
> Persistent=true
> 
> [Install]
> WantedBy=timers.target
> 
> # vim /etc/systemd/system/update-flatpaks.service
> [Unit]
> Description=Update user Flatpaks
> 
> [Service]
> Type=oneshot
> ExecStart=/usr/bin/flatpak update -y
> 
> [Install]
> WantedBy=default.target
> ```
> 
> Enabling the timer will update all the system-wide installed flatpaks. This can be also modified to do the same thing for user installed applications, but executing `/usr/bin/flatpak --user update -y` instead and move the units under `~/.config/systemd/user/`.

Sold. I love this systemd unit. Do you want to make a quick PR to add it to the `alternative_procurement.md` document? It's really good.

2021-10-04 08:35 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +This might appeal to advanced users who agree to spend more time configuring their system in exchange for a system that will require little to no maintenance (especially suited for friends and relati
Good points. The intention of this passage I think (I cannot really comment for @syds-git) but from what I remember reviewing his text with him) was to make the following 3 claims:
- setting up MicroOS takes a little bit more time/effort than setting up Leap or TW (I have never used MicroOS, I have no idea, I am just listening at doors!)
- the tradeoff you get from the above is that you need less time/effort to update
- the tradeoff you get from the above makes MicroOS suitable for friends and relatives with little knowledge _provided_ their  machines are set up by an advanced user with the knowledge.

2021-10-04 08:37 UTC, why-not-try-calmer commented
Thank you very much @apinter for all these comments. I'll stand-by for your replies and then update the document in a single pass, to avoid back-and-forth.

2021-10-04 14:43 UTC, apinter commented on project/docs/safety_usability.md
> +- don't use the "1-click installers" available from https://software.opensuse.org
What I mean is that users shouldn't use it at all on any distros till it is available ^_^

2021-10-04 14:48 UTC, apinter commented on project/docs/safety_usability.md
> +2. Do not manually install important system libraries or codecs directly from _zypper_ or _Yast2_. Use [opi](/best-of-post#codecs) if you must, but prefer software that ship with their own static lib
Ok, gotcha. Yea read it again helped ;)

2021-10-04 14:49 UTC, apinter commented on project/docs/safety_usability.md
> +3. Update every other week or twice a month, not more often. Use `sudo zypper dup`, plus if that applies to you, `flatpak update`.
Sure, can do tomorrow morning.

2021-10-04 15:14 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +2. Do not manually install important system libraries or codecs directly from _zypper_ or _Yast2_. Use [opi](/best-of-post#codecs) if you must, but prefer software that ship with their own static lib
If you had to read it twice, this is a bug. Will simplify.

2021-10-04 15:14 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +- don't use the "1-click installers" available from https://software.opensuse.org
Okay, so it's fine, nothing to change there? I mean this document is specifically about TW.

2021-10-04 15:15 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +3. Update every other week or twice a month, not more often. Use `sudo zypper dup`, plus if that applies to you, `flatpak update`.
<3

2021-10-04 15:16 UTC, why-not-try-calmer commented on project/docs/safety_usability.md
> +This might appeal to advanced users who agree to spend more time configuring their system in exchange for a system that will require little to no maintenance (especially suited for friends and relati
Okay, thanks.

2021-10-05 09:49 UTC, apinter commented on project/docs/safety_usability.md
> +- don't use the "1-click installers" available from https://software.opensuse.org
Yep, fine.

2021-10-05 09:58 UTC, why-not-try-calmer commented
Are we mergeable?

2021-10-06 08:50 UTC, merged