power mgmt: Edit and expand Hibernation section etc.
openSUSE/openSUSE-docs-revamped-temp pull request #73
Opened 2022-01-11 17:29 UTC by sknorr

The previous branches from Liam were a bit of a mess, I have started to separate the software installer and power management changes he made.

These are just the power management things, rebased on top of the current `dev` branch.

I have also reformatted the file to [one-sentence-per-line style](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line), because that will make things more readable and diffable in the future.
I realize that sentence-per-line is not the canonical style for Markdown, but it does have major advantages when working with text in Git and MkDocs actually seems to support it. :)

The following comment from the [original PR](https://github.com/openSUSE/openSUSE-docs-revamped-temp/pull/60/commits/cb200fc1ca52528c2d62de889dba11e08e9da536) are not yet handled, and I am frankly out of my depth on those. The best I could do is to use somewhat softer wording.

```diff
+ * You must have a _dedicated_ swap _partition_.
```
>  Ethanol6 on 21 Oct 2021
> > Does openSUSE default install create a swap partition? Is a swap file an option?
> 
> why-not-try-calmer on 21 Oct 2021
> The Yast2 installer of Leap/TW has too many alternative "views" (Expert, Guided, etc.) to answer this with a Yes or No. What is an absolute Yes is that hibernation requires a swap block, be it a physical partition or a file. If I remember when doing my research on this topic I went for a "partition" by default as it it much easier to use and troubleshoot.

and

```diff
+  * Hibernation will not work if you use a swap _file_ in your root partition instead of a separate swap partition.
```
> Ethanol6 on 21 Oct 2021
> > Is this an openSUSE or BTRFS thing? I use swap files on other distros and hibernation works fine.

2022-01-16 17:55 UTC, why-not-try-calmer requested changes
Same comment -- ready to go, commits optional but desirable

2022-01-16 17:55 UTC, why-not-try-calmer commented on project/docs/power.md
> +When Linux hibernates, it stores the contents of memory in your swap partition. When you next boot the machine, when the kernel starts up, it looks in the swap partition and if it finds a suspend ima
```suggestion
When Linux hibernates, it saves the contents of the memory (running programs, including the current state of your desktop environment) to your swap partition. When you next boot the machine, when the kernel starts up, it looks in the swap partition and if it finds a suspend image there, it reads it back into memory and resumes operation.
```

2022-01-16 17:55 UTC, why-not-try-calmer commented on project/docs/power.md
> +*   If it is partitioned with MBR, the old DOS partitioning scheme:
```suggestion
*   If it is partitioned with MBR, the old DOS partitioning scheme applies:
```

2022-01-17 21:06 UTC, sknorr commented
Both applied, plus a few more edits...

2022-01-17 21:19 UTC, why-not-try-calmer approved these changes

2022-01-17 22:37 UTC, Ethanol6 commented
My original comments about hibernation were possibly confusion between *hibernation* and *suspend*. I know *suspend* works with a swap file.

2022-01-17 22:43 UTC, merged

2022-01-17 23:04 UTC, why-not-try-calmer commented
Thank you both!

2022-01-18 09:48 UTC, sknorr commented
@Ethanol6 

>My original comments about hibernation were possibly confusion between hibernation and suspend. I know suspend works with a swap file.

Suspend-to-RAM should actually also work without a swap file. Suspend-to-disk otoh ... I don't really know. I haven't used that in years.

I know specifically that Ubuntu has recently (some time in the last year) made swap files the default for suspend-to-disk though. Afair, they put quite a bit of effort into making that work for Ubuntu specifically. I also think they don't use a CoW file system (like Btrfs) for the `/` partition by default, not sure whether swap file + CoW file system is a good combo. (As I mentioned, I am thoroughly out of my depth here.)

2022-01-19 03:30 UTC, Ethanol6 commented
>I also think they don't use a CoW file system (like Btrfs) for the `/` partition by default, not sure whether swap file + CoW file system is a good combo.

The default is ext4. According to [this thread](https://askubuntu.com/questions/1206157/can-i-have-a-swapfile-on-btrfs)
it wasn't possible until kernel version 5 and it has to be on a separate subvolume with CoW disabled.