software: Edit software install doc, add AppImage section
openSUSE/openSUSE-docs-revamped-temp pull request #74
Opened 2022-01-11 18:30 UTC by sknorr

Draft, shall replace the software portion of #59 / #60 ... eventually.

2022-01-16 17:49 UTC, why-not-try-calmer requested changes
Thank you very much for the great work on this material. I am very happy this has improved so much over the last weeks. I've made a couple of in-line commit suggestions; let me know if you accept them. 

As always, accepting them is not required for merging, but it may help :)

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    Alternatively, they may only include source code and build scripts, so you must compile them yourself.
```suggestion
    Or they may only include source code and build scripts, in which case you must compile them yourself.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    Alternatively, they may only include source code and build scripts, so you must compile them yourself.
Just more streamlined.

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    *   If the package is provided by one of the official repositories that openSUSE already knows about, such as [download.opensuse.org/update/tumbleweed/](https://download.opensuse.org/update/tumbl
```suggestion
    *   If the package is provided by one of the official repositories, such as [download.opensuse.org/update/tumbleweed/](https://download.opensuse.org/update/tumbleweed/), it will show up in `zypper search <package_name>`.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +The openSUSE project maintains a website where contributors can find software packages for easy installation, especially those built using the _openSUSE Build Service_.
```suggestion
The openSUSE project offers a website where contributors can find software packages for easy installation, especially those built using the _openSUSE Build Service_.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +If a package is available for your version of openSUSE, generally, click the link with the version number.
```suggestion
If a package is available for your version of openSUSE, click the link with the version number.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +If not, you can click on the `.ymp` file in your file manager and YaST should open it.
```suggestion
If the package does not reference your version of openSUSE, you can click on the `.ymp` file in your file manager and YaST should open it.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +__Pros:__
```suggestion
__Pros of official RPMs:__
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +__Pros:__
Or _RPMs provided by official repositories_, just less wordy.

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +*   Has the best performance (startup time and execution speed) of all solutions.
```suggestion
*   Have the best performance (startup time and execution speed) of all solutions.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +*   Uses the lowest amount of RAM and hard drive capacity.
```suggestion
*   Use the lowest amount of RAM and hard drive capacity.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +*   Heavily depends upon the libraries and other dependencies provided by your operating system.
```suggestion
*   RPMs heavily depend upon the libraries and other dependencies provided by your operating system.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +*   Depends on the availability of the distribution packagers and maintainers
```suggestion
*   RPMs depend on the availability of the distribution packagers and maintainers
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +*   Has the best performance (startup time and execution speed) of all solutions.
```suggestion
*   Binaries from third-parties offer the best performance (startup time and execution speed) of all solutions (except for official RPMs, on par with them).
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +_Flatpak_ is a complete solution for installing, updating and running desktop applications from a containerized environment.
```suggestion
_Flatpak_ is a complete solution for installing, updating and running desktop applications from a containerized environment. Flatpaks represent the culmination of combined efforts to offer performant and quality desktop applications compatible with all distributions.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +_Flatpak_ is a complete solution for installing, updating and running desktop applications from a containerized environment.
Some pat on the back of flatpaks might not be out of place.

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +There are many other environment parameters
```suggestion
There are many other environment parameters.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    All Flatpak applications hosted on Flathub have a public repository (often on GitHub) where you read GitHub Issues and participate in the conversation.
```suggestion
    All Flatpak applications hosted on Flathub have a public repository (often on GitHub) where you can read GitHub Issues and participate in the conversation.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +However, you need to do a little more work.
```suggestion
However, you need to do a little manual work.
```

2022-01-16 17:49 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    You have to update your apps yourself, by hand.
```suggestion
    You have to update your apps yourself, manually.
```

2022-01-17 09:40 UTC, sknorr commented on project/docs/alternative_procurement.md
> +    *   If the package is provided by one of the official repositories that openSUSE already knows about, such as [download.opensuse.org/update/tumbleweed/](https://download.opensuse.org/update/tumbl
Good catch, "knows about" is not great. But I'd try this rewording to make it more usefl

```suggestion
    *   If the package is provided by one of the official repositories, which are preconfigured in openSUSE, such as [download.opensuse.org/update/tumbleweed/](https://download.opensuse.org/update/tumbleweed/), it will show up in `zypper search <package_name>`.
```

2022-01-17 09:41 UTC, sknorr commented on project/docs/alternative_procurement.md
> +__Pros:__
Hm, this is inconsistent with the "Pros"/"Cons" headlines elsewhere in the file...

2022-01-17 09:46 UTC, sknorr commented on project/docs/alternative_procurement.md
> +We use "third-party remote providers" to mean for websites, services or remote machines offering automatic installation using scripts provided along with the desired application.
```suggestion
We use "third-party remote providers" to mean websites, services or remote machines offering automatic installation using scripts provided along with the desired application.
```

2022-01-17 09:48 UTC, sknorr commented on project/docs/alternative_procurement.md
> +If not, you can click on the `.ymp` file in your file manager and YaST should open it.
Mmh, no, this is not what it's supposed to mean -- we're talking about browser not configured to open YMP files automatically after download.

2022-01-17 09:50 UTC, sknorr commented on project/docs/alternative_procurement.md
> +    Alternatively, they may only include source code and build scripts, so you must compile them yourself.
1. I agree the sentence could use some work.
2. I am not sure I agree about the suggestion.

Counter-suggestion:
```suggestion
    Alternatively, they may only include source code and build scripts which you have to compile yourself.
```

2022-01-17 09:55 UTC, sknorr commented on project/docs/alternative_procurement.md
> +*   Favour __Flatpaks__ if you:
@why-not-try-calmer For the record, are you using British English or American in these docs? (I left the British version here -- official SUSE docs use American English though.)

2022-01-17 09:59 UTC, sknorr commented on project/docs/alternative_procurement.md
> +_Flatpak_ is a complete solution for installing, updating and running desktop applications from a containerized environment.
Tbh, that sounds like marketing (not docs) and leaves a lot of open questions, like: "Combined efforts" of whom? If Flatpaks are the culmination of performance, why do we say they are less performant than RPMs? ...

2022-01-17 10:09 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +If not, you can click on the `.ymp` file in your file manager and YaST should open it.
Oh I see, my bad.

2022-01-17 10:12 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +_Flatpak_ is a complete solution for installing, updating and running desktop applications from a containerized environment.
Adjusted.

2022-01-17 10:14 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +*   Favour __Flatpaks__ if you:
Let's stick to American.

2022-01-17 10:14 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +*   Favour __Flatpaks__ if you:
```suggestion
*   Favor __Flatpaks__ if you:
```

2022-01-17 10:16 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    *   If the package is provided by one of the official repositories that openSUSE already knows about, such as [download.opensuse.org/update/tumbleweed/](https://download.opensuse.org/update/tumbl
Ok.

2022-01-17 10:16 UTC, sknorr commented
> Thank you very much for the great work on this material. I am very happy this has improved so much over the last weeks. I've made a couple of in-line commit suggestions; let me know if you accept them.

Thanks for all the suggestions! I applied a number of them & commented the others.

2022-01-17 14:05 UTC, sknorr commented on project/docs/alternative_procurement.md
> +*   You need maximal performance/minimal usage.
```suggestion
*   You need maximal performance and minimal resource usage.
```

2022-01-17 14:44 UTC, why-not-try-calmer commented
I've applied the commit about referencing the flatpak documentation.

As far as I can see, this is mergeable material. Thanks to you @sknorr and @lproven for all your work!

2022-01-17 14:44 UTC, merged