Remove obsolete docs
openSUSE/openSUSE-docs-revamped-temp pull request #84
Opened 2022-05-25 20:49 UTC by apinter

Addressing #81

2022-05-27 05:22 UTC, why-not-try-calmer commented
Hello, thanks for this, I appreciate this is evolving into something more constructive than your initial suggestion implied. Comments to follow.

2022-05-27 05:42 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> -## Snaps
I don't like snaps, never have, never will. But wouldn't be more judicious to gently discourage the users to use snaps, instead of not mentioning them at all? This is a pattern I've tried to follow in the docs: when facing the choice between red flags and no flag, I've tried to go with the red flags because the effects it has is more controllable than the no-flag option.

2022-05-27 05:42 UTC, why-not-try-calmer commented on project/docs/codecs.md
>  ## Installing Codecs
Appropriate deletion, thanks for this.

2022-05-27 05:42 UTC, why-not-try-calmer commented on project/docs/install_podman.md
> -## What is Podman
I like this article because let's be real, oS is loved by sysadmins for a reason. Isn't there a replacement you could suggestion?  I have myself gathered notes from left and right but they are too specific to my use case to be a suitable replacement for this article, which has more generality.

2022-05-27 05:42 UTC, why-not-try-calmer commented on project/docs/tw-cli.md
> -## tumbleweed-cli
Ah, no better way to start the day than with a fresh argument about tw-cli XD. Look, when I look around I see this:
- https://bugzilla.suse.com/show_bug.cgi?id=1199924: that's TW lead maintainer taking care of a person who is also to be TW maintainer over some issue, and at no point does it seem that tw-cli is a monstruosity that does not merit to exist;
- https://bugzilla.suse.com/show_bug.cgi?id=1146085: same as the previous one

Of course I could have cherry-picked more issues: it would still not have shown that tw-cli is good (or bad). My point is simply that some people more knowledgeable than me seem to not keen on using it / supporting people who use it. I see also that this tool has not been removed from Factory, even after the vehement argument developed in #17. 

Also I see posts like this:
- https://www.reddit.com/r/openSUSE/comments/ptqo2u/comment/hdxzeq1/?utm_source=share&utm_medium=web2x&context=3: also from a TW lead dev

So what I see is that some "senior" people use it, take it for granted, and are happy having it exist in Factory. I see also that some other people hate it, but it's fair to say that it's not a black or white situation.

What makes it not a black or white situation is clearly that it has a safe use case:
- cherry-picking a more recent TW snapshot that is less recent than the latest TW snapshot (that's what I've tried to make crystal clear in this article)

...and it also has an unsafe use case:
- rolling back and forth between TW snaps

which is also warned against in this article. As with my first comment, since this package is used, talked outside of this docs and exists in Factory, people are going to continue using them. So IMHO it's more serviceable to the users to present it with red flags than to no present it at all (same reasoning as in my first comment to this PR).

2022-05-27 05:42 UTC, why-not-try-calmer commented on project/docs/zstd.md
>  ## Enable zstd compression
Thanks.

2022-05-27 06:20 UTC, apinter commented on project/docs/alternative_procurement.md
> -## Snaps
You're welcome to do so and you've been encouraged to do so for a while. I would not even mention it hence the removal. Soon enough AppImages will be unsupported as well, it is in fact already discouraged.

2022-05-27 06:21 UTC, apinter commented on project/docs/install_podman.md
> -## What is Podman
This should be maintained which I refused to do so here.

2022-05-27 06:25 UTC, why-not-try-calmer commented on project/docs/install_podman.md
> -## What is Podman
Sure, my question: Do you know of any material that could be a suitable replacement, either in-place or as a reference?

2022-05-27 06:25 UTC, apinter commented on project/docs/tw-cli.md
> -## tumbleweed-cli
This has been requested a lot from you, not going into this again, the reasons have been explained a lot. The wiki is a widely known unofficial documentation, this is not. Thus my suggestion to move it out of the openSUSE org where you could write anything you want.

2022-05-27 06:28 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> -## Snaps
Does that mean that you'd be OK if this part mentioned snaps for recommending against using them instead of removing all references to snaps?

2022-05-27 06:29 UTC, why-not-try-calmer commented on project/docs/tw-cli.md
> -## tumbleweed-cli
I don't follow. No one is talking about the wikis here. Check out the links.

2022-05-27 06:53 UTC, SingletonW commented on project/docs/tw-cli.md
> -## tumbleweed-cli
sending an email does not sound to unreasonable. would that suit @apinter ? I can send it

2022-05-27 06:57 UTC, SingletonW commented on project/docs/zstd.md
>  ## Enable zstd compression
@apinter any info on why it is not supported? I would like to add this info to make sure users understand why

2022-05-27 11:08 UTC, apinter commented on project/docs/install_podman.md
> -## What is Podman
No.

2022-05-27 11:11 UTC, apinter commented on project/docs/tw-cli.md
> -## tumbleweed-cli
This project suppose to help users facing issue, why cause more? I don't understand or follow your reasoning. You're posing under the openSUSE flag as a responsible documentation team, but refuse to remove a fully unsupported piece of document that has been requested for a while now. It makes it to Factory because it makes it, nothing to do about it, but here you could, but refuse to do so... who understands this?
It is not a supported use case, you should do the right thing and remove it not advertise it.

2022-05-27 11:31 UTC, why-not-try-calmer commented on project/docs/tw-cli.md
> -## tumbleweed-cli
Thanks for asking, the reasoning is simple. There are three groups of people:
a. users who like / use / appreciate this tool, among which maintainers or lead devs as suggested by some of the links above
b. maintainers who directly _support_ this tool (Jimmy, the author) or that support people declaring issues connecting with this tool but for whom the tool is not the culprit (see the bugzilla items linked above)
c. maintainers or users who don't like this tool, want to see dropped, or don't want to see it supported let alone support it themselves (Richard, Simon, you)

I have no stakes at all in this situation. I don't care one way or another. But that doesn't mean I should try to be fair and impartial, and to have this docs reflect as much impartiality as can be. For this reason I am reluctant to tell people from the (a) and (b) groups: Look, people from group (c) have a strong distaste for this this tool, therefore we're going to make sure to "cancel" it from this docs. I would be much happier telling people from (a), (b) _and_ (c): on way of using this tool is wrong, another way of using it is fine, here's what you know to use it the right way.

2022-05-27 17:24 UTC, apinter commented on project/docs/tw-cli.md
> -## tumbleweed-cli
> c. maintainers or users who don't like this tool, want to see it dropped, or don't want to see it supported let alone support it themselves (Richard, Simon, you).

It is already not supported and never was so not sure where you get the idea from that it is.

> Now I might be wrong in my assessment of the facts; perhaps all the core devs stand in staunch opposition to this tool. My suggestion was: let's ask them and if I am wrong, let's have this removed.

You had months upon months to ask and take the advice, you didn't. This project is not serving user needs as it should by suggesting supported use cases. 

---
Lets look at your links then which I admin I did skip :

> https://bugzilla.suse.com/show_bug.cgi?id=1199924: that's TW lead maintainer taking care of a person who is also to be TW maintainer over some issue, and at no point does it seem that tw-cli is a monstruosity that does not merit to exist;

Devs talking to devs, not users, and yes there is a major difference.

> https://bugzilla.suse.com/show_bug.cgi?id=1146085: same as the previous one

"IMHO, this is far out of what TW is supposedly doing." / Dom /. Not sure what should convince anyone here.

> https://www.reddit.com/r/openSUSE/comments/ptqo2u/tumbleweedcli_is_not_a_good_safety_net/hdxzeq1/?utm_source=share&utm_medium=web2x&context=3

"Shouldn't be downgraded". Doc never mentions this as it doesn't mention any of the warnings..... 

I don't feel convinced maybe because I know what I'm talking about? Idk. All I see is you not letting this through no matter who says what ¯\_(ツ)_/¯

2022-05-27 19:05 UTC, SingletonW commented on project/docs/tw-cli.md
> -## tumbleweed-cli
hi @apinter, can I ask: what solution do you have in mind for users who want to upgrade in a more controlled way than just running down to the latest tw snapshot? that's how I understand https://www.reddit.com/r/openSUSE/comments/ptqo2u/tumbleweedcli_is_not_a_good_safety_net/hdxzeq1/?utm_source=share&utm_medium=web2x&context=3: it's fine to use tw-cli for picking a specific target forward snap. That might not be the way you use tw. But I know some users who keep upgrades on a hold, waiting for more "testing" for the community. Wouldn't these users have a use case?

Besides I think @why-not-try-calmer has said he agreed with you that using tw-cli for rolling back was unsafe. insisting on that in the docs shouldn't be too difficult

2022-05-27 20:29 UTC, why-not-try-calmer commented on project/docs/tw-cli.md
> -## tumbleweed-cli
So apparently the main developers of this tool have stopped providing the service that allowed users to review snapshots ahead of upgrading. The article already mentioned that this tool was not statistically very elaborate, but the fact that their infrastructure has been down for so long suggests that, contrary to what I believed, it's unclear whether there is a plan to keep supporting even the safe ("cherry-pick your next snap") way of using it. For me this is enough evidence in favour of dropping it. Moving back to the details.

2022-05-27 20:34 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> -## Snaps
Sorry, I didn't understand if you were Ok with adding red flags instead of removing simpliciter. Also, I've done some research but I couldn't find evidence that snaps were not recommended on either Leap or Tumbleweed. Do you have evidence that this is the case? Or is it just MicroOS that does not support them?

2022-05-27 20:35 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    AppImages are not recommended, and some _openSUSE_ distributions like _MicroOS_ [not even supporting it](https://bugzilla.opensuse.org/show_bug.cgi?id=1198653)
I've done a little research but I couldn't find evidence that AppImages were not recommended on either Leap or Tumbleweed. Do you have evidence that this is the case? Or is it just MicroOS that does not support them?

2022-05-28 07:06 UTC, apinter commented on project/docs/tw-cli.md
> -## tumbleweed-cli
@SingletonW 
> hi @apinter, can I ask: what solution do you have in mind for users who want to upgrade in a more controlled way than just running down to the latest tw snapshot?

If you're not familiar with Tumbleweed or how to use a rolling distro than I don't understand why do you want to write docs about it? :thinking: 
Please don't get this the wrong way, I don't know you or your capabilities/expertise so this not an offense or anything, but if you seriously have to ask that question that would suggest to me that you didn't read every article this project has already put out, and you don't have a deep enough understanding on how TW works.
To give you a TL;DR: TW is bleeding edge rolling, that means that new version of packages will appear fairly frequently (weekly we have an avg. of 3 new snapshots, depending on what goes in from Factory). The users have a few options to control how they update:
- Daily check for updates and apply what is available,
- Weekly check for updates and apply in a big chunk (say avg. of 800 packages),
- Monthly is doable, but not recommended. 

I do weekly updates for instance on my remaining TW desktops and servers in prod (regularity also depends on the severity of vulnerabilities), and that proved me right (so far) in the past 6 years I've been using TW, or the 5 years prior to that using Arch. To avoid issues - and this is a major diff compared to other rolling distros like Arch and friends - we have Snapper. If anything breaks you can just roll back. If  If you have kernel issues you can boot with an older kernel as well (pretty sure we did a write up on this one too, read it). If you want to stick with different versions use containers, but you will also have to deal with the security issues unmaintained images carry so that is a pain for the user to bare.  Or an even more simple solution is to not use a rolling distro at all, Leap is still very much around. 
Another option is to use MicroOS like I do. That spares users from most of the pain points TW has in this regard, but immutable systems are really not for everyone.
I also have a __personal__ way of doing this which is [download updates daily](https://gist.github.com/apinter/2a056b649a0d643575513a000cbbb2bf), but I decide when I apply it. Official? Probably closer than `tw-cli`, but it is close. My Flatpaks are [updated daily](https://gist.github.com/apinter/c6c1f786414ec8f67e21d39629efbedf), and also applied daily, but whole different story. Non of these units are in the openSUSE org for a reason. It is opinionated.

> that's how I understand https://www.reddit.com/r/openSUSE/comments/ptqo2u/tumbleweedcli_is_not_a_good_safety_net/hdxzeq1/?utm_source=share&utm_medium=web2x&context=3: it's fine to use tw-cli for picking a specific target forward snap. 

Your understanding is not wrong, however, you miss the warning at the end which is also not included in the doc leading back to the core subject of me opening the issue and the PR == the docs are unmaintained and has no regular contributors (the project had 6 PRs - from which two went in to  MicroOS which was removed anyway - this year if I see that right and did not reach it's goals it set in 2021 so spare me from the previously provided answers please).

> That might not be the way you use tw. But I know some users who keep upgrades on a hold. They'd wait for more "testing" for the community. Wouldn't these users have a use case?

And we reach the part where it becomes clear that you lack the crucial understanding of the whole problem. This is not about opinions, but what is a supported use case by the creators of the distros (which we about 6 of, and by the fall we will probably have 7 with ALP), and what isn't. If you want to give users options do it on the [wiki](en.opensuse.org) which is known to be full with opinionated information random users put there. However, this project was not intended to fall into that pit when we started it, but to provide good, quality documentation that is in line with the supported use cases, doesn't recommend risky tools that can potentially break user land or leave it vulnerable, and well maintained. Currently it is not hence this whole conversation. Pointless to keep it around if it fails to do that since we already have the wiki. This whole back-and-forth with this project was the reason of me refusing to write docs here, and to join the Board. Not fun for anyone.

@SingletonW I noticed that you take things personally so please don't (now I wonder if I should start with this, but meh), it is not an "attack" on you or "gatekeeping" or whatever. If you need an intro to TW I'm happy to do answer your questions, the [Bar](https://meet.opensuse.org/bar) is always open or hit me up on Telegram (same handle). 
How great that we spammed full the PR instead of talking under the issue... will look great :upside_down_face: 

---

> So apparently the main developers of this tool have stopped providing the service that allowed users to review snapshots ahead of upgrading. The article already mentioned that this tool was not statistically very elaborate, but the fact that their infrastructure has been down for so long (I didn't know) suggests that, contrary to what I believed, it's unclear whether there is a plan to keep supporting even the safe ("cherry-pick your next snap") way of using it. For me this is enough evidence in favour of dropping it. Moving back to the details.

Glad that one way or the other we reached an agreement (or at least I think we did).

2022-05-28 08:11 UTC, SingletonW commented on project/docs/zstd.md
>  ## Enable zstd compression
![Capture d’écran du 2022-05-28 10-10-44](https://user-images.githubusercontent.com/97265592/170816858-ce81ec40-30ca-4f8e-8a81-c2d2ea9cd0f8.png)

2022-05-28 08:12 UTC, SingletonW commented on project/docs/zstd.md
>  ## Enable zstd compression
mind fixing this?

2022-05-28 08:29 UTC, why-not-try-calmer requested changes
So still missing are:
- evidence that zstd is not supported on Leap (if it's the _method_ for applying compression that is not supported, that's easy to fix, but we need more info)
- evidence / explanation that AppImages are "not supported" or "officially recommended against" (I know a ton of non-microOS users who use AppImages when flatpaks are not available so better be sure what we're telling them.

2022-05-28 15:21 UTC, apinter commented on project/docs/zstd.md
>  ## Enable zstd compression
Yep, your right, messed up the version numbers.

2022-05-28 15:39 UTC, apinter commented on project/docs/alternative_procurement.md
> +    AppImages are not recommended, and some _openSUSE_ distributions like _MicroOS_ [not even supporting it](https://bugzilla.opensuse.org/show_bug.cgi?id=1198653)
One thing is that MicroOS is absolutely not supporting it, the other that it is not recommended to use it. The "not recommended" bit is that using an AppImage requires the user to pretty much blindly trust the source while AppImages are not offering any meaningful ways to verify that they're coming from a trusted source. This also indicates that they can't be checked if they're running anything that the user doesn't want to run willingly. OOTB it also doesn't have any sandboxing capabilities unlike Flatpaks. AppImages generally not offering a generally easy way to update them, leaving the user with a potentially vulnerable software on the long run.
It is just not a reliable way of running applications compared to the alternatives. Hope this clarifies.

2022-05-31 10:18 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    AppImages are not recommended, and some _openSUSE_ distributions like _MicroOS_ [not even supporting it](https://bugzilla.opensuse.org/show_bug.cgi?id=1198653)
```suggestion
    AppImages are executable, file-like application bundles which are somewhat controversial in the Linux community for their lack of UI consistency with the host system and for the security risks they might incur. Furthermore they are [not supported on MicroOS](https://bugzilla.opensuse.org/show_bug.cgi?id=1198653). For these reasons we recommend preferring other software procurement methods when possible. 
```

2022-06-09 20:31 UTC, SingletonW commented on project/docs/alternative_procurement.md
> +    AppImages are not recommended, and some _openSUSE_ distributions like _MicroOS_ [not even supporting it](https://bugzilla.opensuse.org/show_bug.cgi?id=1198653)
@why-not-try-calmer shouldn't we make it more explicit why AppImages are not recommended ?
also is this PR ready or is there something else to change/ review ?

2022-06-09 22:33 UTC, why-not-try-calmer approved these changes

2022-06-09 22:35 UTC, why-not-try-calmer commented on project/docs/alternative_procurement.md
> +    AppImages are not recommended, and some _openSUSE_ distributions like _MicroOS_ [not even supporting it](https://bugzilla.opensuse.org/show_bug.cgi?id=1198653)
Unless someone disagrees, this is 'merge material' to me!

2022-06-14 10:23 UTC, merged