Flatpak/flathub user install and Nvidia auto-detect
openSUSE/openSUSE-docs-revamped-temp pull request #86
Opened 2022-05-28 19:15 UTC by Xathros1

adding the option of a user installation of the flathub repo which allows auto-updates, which is default with e.g. Fedora and other distros

Nvidia drivers: adding under command line the option to use `zypper install-new-recommends --repo nvidia` as a way to auto-detect the users hardware.

2022-05-28 19:26 UTC, Xathros1 commented on project/docs/best_of_post.md
> +dd the flatpak repo as user to enable auto-updates without the need of a root password:
typo

2022-05-28 21:29 UTC, why-not-try-calmer commented
Thank you very much for your work, will take a look!

2022-05-30 13:48 UTC, why-not-try-calmer requested changes
Good stuff, may I ask you if you'd agree to rename your branch from `dev` to something that corresponds to the change you're submitting, i.e. `updating flatpack/flahub`? The convention and workflows is that all PRs should come from a branch that wears the changes "on its sleeves". (You previous PRs was accepted as is because it was your first, but it's better to follow these conventions :)

2022-05-30 13:48 UTC, why-not-try-calmer commented on project/docs/best_of_post.md
> +dd the flatpak repo as user to enable auto-updates without the need of a root password:
```suggestion
add the flatpak repo as user to enable auto-updates without the need of a root password: 
```

2022-05-30 13:48 UTC, why-not-try-calmer commented on project/docs/install_proprietary.md
> +2. To auto-detect and install the right driver for your hardware, run: `sudo zypper install-new-recommends --repo nvidia` Alternatively you can also specify which version via: `sudo zypper in x11-vid
```suggestion
2. To auto-detect and install the right driver for your hardware, run:
   `sudo zypper install-new-recommends --repo nvidia` Alternatively you can also specify which version with:
   `sudo zypper in x11-video-nvidiaG06` or 
   `sudo zypper in x11-video-nvidiaG05` or 
   `sudo zypper in x11-video-nvidiaG04` (you can use `zypper se -s x11-video-nvidia` to help you determine which driver best fits your hardware`).
```

2022-05-30 17:12 UTC, Xathros1 commented on project/docs/best_of_post.md
> +dd the flatpak repo as user to enable auto-updates without the need of a root password:
how should I do that now that I've created the PRs? Also I've got multiple changes?

2022-05-30 17:16 UTC, why-not-try-calmer commented on project/docs/best_of_post.md
> +dd the flatpak repo as user to enable auto-updates without the need of a root password:
> how should I do that now that I've created the PRs? Also I've got multiple changes?

I suggest that you accept / apply the changes. This should update your local branch `dev`. Then you'd simply create a new branch from it.

2022-05-30 17:47 UTC, why-not-try-calmer commented
Okay, continuing to #87 (thanks for renaming)

2022-05-30 17:47 UTC, closed without merging